SuLugar/SuLugar/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using SuLugar.Interfaces;
using SuLugar.ViewModels.Catalog;
using SuLugar.ViewModels.Checkouts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuLugar.Controllers
{
    public class CatalogController : Controller
    {
        private ILibraryAsset _assets;
        private ICheckout _checkouts;

        public CatalogController(ILibraryAsset assets, ICheckout checkouts)
        {
            _assets = assets;
            _checkouts = checkouts;
        }

        public IActionResult Index()
        {
            var assetModels = _assets.GetAll(); // Tomo todos los datos del modelo

            // Se lo mando al ViewModel y extraigo los datos que necesito 
            var listingResult = assetModels
                .Select(res => new AssetIndexListingModel
                {
                    Id = res.Id,
                    ImageUrl = res.ImageUrl,
                    AuthorOrDirector = _assets.GetAuthorOrDirector(res.Id),
                    DeweyCallNumber = _assets.getDeweyIndex(res.Id),
                    Title = res.Title,
                    Type = _assets.GetType(res.Id)
                });

            // Instancio el ViewModel final con los datos que saque arriba y se lo mando como parámetro IEnumerable
            var model = new AssetIndexModel()
            {
                Assets = listingResult
            };

            // Retorno la vista
            return View(model);
        }

        //Catalog/Detail/123
        public IActionResult Detail(int id)
        {
            var asset = _assets.GetById(id);

            var currentHolds = _checkouts.GetCurrentHolds(id)
                .Select(a => new AssetHoldModel // Collection
                {
                    HoldPlaced = _checkouts.GetCurrentHoldPlaced(a.Id),
                    PatronName = _checkouts.GetCurrentHoldPatronName(a.Id)
                });

            var model = new AssetDetailModel
            {
                AssetId = id,
                Title = asset.Title,
                Year = asset.Year,
                Cost = asset.Cost,
                Status = asset.Status.Name,
                ImageUrl = asset.ImageUrl,
                AuthorOrDirector = _assets.GetAuthorOrDirector(id),
                CurrentLocation = _assets.GetCurrentLocation(id).Name,
                DeweyCallNumber = _assets.getDeweyIndex(id),
                CheckoutHistory = _checkouts.GetCheckOutHistory(id),
                ISBN = _assets.GetIsbn(id),
                LatestCheckout = _checkouts.GetLatestCheckout(id),
                PatronName = _checkouts.GetCurrentCheckoutPatron(id),
                CurrentHold = currentHolds
            };

            return View(model);
        }

        public IActionResult Checkout(int id)
        {
            var asset = _assets.GetById(id);

            var model = new CheckOutModel
            {
                AssetId = id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId = "",
                isCheckedOut = _checkouts.IsCheckedOut(id)
            };

            return View(model);
        } 

        public IActionResult CheckIn(int id)
        {
            _checkouts.CheckInItem(id);
            return RedirectToAction("Detail", new { id = id });
        }

        public IActionResult Hold(int id)
        {
            var asset = _assets.GetById(id);

            var model = new CheckOutModel
            {
                AssetId = id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId = "",
                isCheckedOut = _checkouts.IsCheckedOut(id),
                HoldCount = _checkouts.GetCurrentHolds(id).Count()
            };

            return View(model);
        }

        public IActionResult MarkLost(int assetId)
        {
            _checkouts.MarkLost(assetId); 

            return RedirectToAction("Detail", new { id = assetId });
        }

        public IActionResult MarkFound(int assetId)
        {
            _checkouts.MarkFound(assetId); 

            return RedirectToAction("Detail", new { id = assetId });
        }

        [HttpPost]
        public IActionResult PlaceCheckout(int assetId, int libraryCardId)
        {
            _checkouts.CheckOutItem(assetId, libraryCardId); // Creo un nuevo checkout y mando a Detail

            return RedirectToAction("Detail", new { id = assetId });
        }

        [HttpPost]
        public IActionResult PlaceHold(int assetId, int libraryCardId)
        {
            _checkouts.PlaceHold(assetId, libraryCardId); 

            return RedirectToAction("Detail", new { id = assetId });
        }

    }
}

SuLugar/SuLugar/Controllers/PatronController.cs
using Microsoft.AspNetCore.Mvc;
using SuLugar.Interfaces;
using SuLugar.Models;
using SuLugar.ViewModels.Patron;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuLugar.Controllers
{
    public class PatronController : Controller
    {
        private IPatron _patron;

        // CTR
        public PatronController(IPatron patron)
        {
            _patron = patron;
        }


        public IActionResult Index()
        {
            var allPatrons = _patron.GetAll(); 


            // ViewModel 1
            var patronModels = allPatrons
                .Select(patron => new PatronDetailModel
                {
                    Id = patron.Id,
                    Firstname = patron.FirstName ?? "No provisto",
                    Lastname = patron.LastName ?? "No provisto",
                    LibraryCardId = patron.LibraryCard.Id,
                    OverdueFees = patron.LibraryCard.Fees,
                    HomeLibrary = patron.HomeLibraryBranch.Name
                }).ToList();

            // ViewModel 2 list
            var model = new PatronIndexModel()
            {
                Patrons = patronModels
            };

            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var patron = _patron.Get(id);
            try
            {
                var patronDetail = new PatronDetailModel()
                {
                    Lastname = patron.LastName,
                    Firstname = patron.FirstName,
                    Address = patron.Address,
                    HomeLibrary = patron.HomeLibraryBranch.Name,
                    MemberSince = patron.LibraryCard.Created,
                    OverdueFees = patron.LibraryCard.Fees,
                    LibraryCardId = patron.LibraryCard.Id,
                    Telephone = patron.Telephone,
                    AssetsCheckedOut = _patron.GetCheckouts(id).ToList() ?? new List<Checkout>(),
                    CheckoutHistory = _patron.GetCheckoutHistory(id),
                    Holds = _patron.GetHolds(id)
                };

                return View(patronDetail);
            }
            catch(Exception e)
            {
                throw e;
            }

            
        }

    }
}

SuLugar/SuLugar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuLugar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.14.1/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>


</head>
<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="custom-header mdl-layout__header mdl-layout__header--waterfall">
            <div class="mdl-layout__header-row">
                <span class="mdl-layout-title logo"><a href="/">Su Lugar Library</a></span>
                <div class="mdl-layout-spacer"></div>
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                <a class="mdl-navigation__link" asp-controller="Patron" asp-action="Index">Patrons</a>
                <a class="mdl-navigation__link" asp-controller="Branch" asp-action="Index">Branches</a>

                <a class="mdl-navigation__link" asp-controller="Account" asp-action="Logout">Logout</a>
                <a class="mdl-navigation__link" asp-controller="Account" asp-action="Login">Login</a>
                </nav>
            </div>
        </header>
        <div class="page-content">
            @RenderBody()
        </div>
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.14.1/js/mdb.min.js"></script>
    @RenderSection("Scripts", required: false)
    @RenderSection("Styles", required: false)
</body>
</html>